.TH MYCP 1 "September 2025" "My Project" "User Commands"
.SH NAME
mycp \- a simple implementation of the cp command
.SH SYNOPSIS
.B mycp
.RI source_file destination_file
.SH DESCRIPTION
The
.B mycp
command copies the contents of
.I source_file
to
.I destination_file .
If the destination file already exists, its contents are overwritten.

Unlike the standard UNIX
.B cp
utility, this version is a simplified implementation created
as part of this project.
.SH AUTHOR
Your Name <malik>
