.TH MYCAT 1 "September 2025" "My Project" "User Commands"
.SH NAME
mycat \- a simple implementation of the cat command
.SH SYNOPSIS
.B mycat
.RI [ filename ... ]
.SH DESCRIPTION
The
.B mycat
command reads files sequentially, writing them to standard output.
It is similar to the standard UNIX
.B cat
utility, but implemented as part of this project.

Multiple filenames may be specified. If no filename is given,
.B mycat
reads from standard input.
.SH AUTHOR
Your Name <your.email@example.com>
